// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopeering/peer/proto/peer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/iotaledger/hive.go/autopeering/peer/service/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Minimal encoding of a peer
type Peer struct {
	// public key used for signing
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// string form of the peers ID
	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	// services supported by the peer
	Services             *proto1.ServiceMap `protobuf:"bytes,3,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a3718f3e1a3ddf, []int{0}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Peer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Peer) GetServices() *proto1.ServiceMap {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*Peer)(nil), "proto.Peer")
}

func init() {
	proto.RegisterFile("autopeering/peer/proto/peer.proto", fileDescriptor_49a3718f3e1a3ddf)
}

var fileDescriptor_49a3718f3e1a3ddf = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2c, 0x2d, 0xc9,
	0x2f, 0x48, 0x4d, 0x2d, 0xca, 0xcc, 0x4b, 0xd7, 0x07, 0xd1, 0xfa, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x60, 0xa6, 0x1e, 0x98, 0x29, 0xc4, 0x0a, 0xa6, 0xa4, 0x74, 0x30, 0x54, 0x16, 0xa7, 0x16, 0x95,
	0x65, 0x26, 0xa7, 0x42, 0x75, 0x40, 0x79, 0x10, 0x4d, 0x4a, 0x29, 0x5c, 0x2c, 0x01, 0x40, 0x35,
	0x42, 0xb2, 0x5c, 0x5c, 0x05, 0xa5, 0x49, 0x39, 0x99, 0xc9, 0xf1, 0xd9, 0xa9, 0x95, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x9c, 0x10, 0x11, 0xef, 0xd4, 0x4a, 0x21, 0x3e, 0x2e, 0xa6, 0xcc,
	0x02, 0x09, 0x26, 0xa0, 0x30, 0x67, 0x10, 0x90, 0x25, 0xa4, 0xcb, 0xc5, 0x01, 0x35, 0xa7, 0x58,
	0x82, 0x19, 0x28, 0xca, 0x6d, 0x24, 0x08, 0x31, 0x50, 0x2f, 0x18, 0x22, 0xec, 0x9b, 0x58, 0x10,
	0x04, 0x57, 0xe2, 0x64, 0x16, 0x65, 0x92, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
	0xab, 0x9f, 0x99, 0x5f, 0x92, 0x98, 0x93, 0x9a, 0x92, 0x0e, 0x74, 0x5a, 0x46, 0x66, 0x59, 0xaa,
	0x5e, 0x7a, 0xbe, 0x3e, 0x76, 0xdf, 0x25, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6d, 0x8f, 0x66, 0x46, 0xfe, 0x00, 0x00, 0x00,
}
