package iotago

// Code generated by go generate; DO NOT EDIT. Check gen/ directory instead.

const (
	// ExampleNameLength defines the length of an ExampleName.
	ExampleNameLength = 32
)

var (
	EmptyExampleName = ExampleName{}
)

// ExampleName is a 32 byte hash value.
type ExampleName [ExampleNameLength]byte

func (e ExampleName) ExampleFeature() string {
	return "ExampleFeature"
}
