// Code generated by "stringer -type=TypeDenotationType"; DO NOT EDIT.

package serializer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeDenotationUint32-0]
	_ = x[TypeDenotationByte-1]
	_ = x[TypeDenotationNone-2]
}

const _TypeDenotationType_name = "TypeDenotationUint32TypeDenotationByteTypeDenotationNone"

var _TypeDenotationType_index = [...]uint8{0, 20, 38, 56}

func (i TypeDenotationType) String() string {
	if i >= TypeDenotationType(len(_TypeDenotationType_index)-1) {
		return "TypeDenotationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}

	return _TypeDenotationType_name[_TypeDenotationType_index[i]:_TypeDenotationType_index[i+1]]
}
