// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Blacklister is an autogenerated mock type for the Blacklister type
type Blacklister struct {
	mock.Mock
}

// AddToBlacklist provides a mock function with given fields: _a0
func (_m *Blacklister) AddToBlacklist(_a0 string) {
	_m.Called(_a0)
}

// PeerBlacklisted provides a mock function with given fields: peer
func (_m *Blacklister) PeerBlacklisted(peer string) bool {
	ret := _m.Called(peer)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(peer)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
