// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	identity "github.com/iotaledger/hive.go/identity"
	mock "github.com/stretchr/testify/mock"

	net "net"

	server "github.com/iotaledger/hive.go/autopeering/server"
)

// HandlerFunc is an autogenerated mock type for the HandlerFunc type
type HandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *HandlerFunc) Execute(_a0 *server.Server, _a1 *net.UDPAddr, _a2 *identity.Identity, _a3 []byte) (bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*server.Server, *net.UDPAddr, *identity.Identity, []byte) bool); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*server.Server, *net.UDPAddr, *identity.Identity, []byte) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
