// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	server "github.com/iotaledger/hive.go/autopeering/server"
	mock "github.com/stretchr/testify/mock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// ProtoReflect provides a mock function with given fields:
func (_m *Message) ProtoReflect() protoreflect.Message {
	ret := _m.Called()

	var r0 protoreflect.Message
	if rf, ok := ret.Get(0).(func() protoreflect.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protoreflect.Message)
		}
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Message) Type() server.MType {
	ret := _m.Called()

	var r0 server.MType
	if rf, ok := ret.Get(0).(func() server.MType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(server.MType)
	}

	return r0
}
