// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TrafficShaping is an autogenerated mock type for the TrafficShaping type
type TrafficShaping struct {
	mock.Mock
}

// RateLimit provides a mock function with given fields:
func (_m *TrafficShaping) RateLimit() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
