// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: autopeering/ars/proto/ars.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ars struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// value of the salt
	Ars []float64 `protobuf:"fixed64,1,rep,packed,name=ars,proto3" json:"ars,omitempty"`
	// expiration time of the salt
	ExpTime uint64 `protobuf:"fixed64,2,opt,name=exp_time,json=expTime,proto3" json:"exp_time,omitempty"`
}

func (x *Ars) Reset() {
	*x = Ars{}
	if protoimpl.UnsafeEnabled {
		mi := &file_autopeering_ars_proto_ars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ars) ProtoMessage() {}

func (x *Ars) ProtoReflect() protoreflect.Message {
	mi := &file_autopeering_ars_proto_ars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ars.ProtoReflect.Descriptor instead.
func (*Ars) Descriptor() ([]byte, []int) {
	return file_autopeering_ars_proto_ars_proto_rawDescGZIP(), []int{0}
}

func (x *Ars) GetArs() []float64 {
	if x != nil {
		return x.Ars
	}
	return nil
}

func (x *Ars) GetExpTime() uint64 {
	if x != nil {
		return x.ExpTime
	}
	return 0
}

var File_autopeering_ars_proto_ars_proto protoreflect.FileDescriptor

var file_autopeering_ars_proto_ars_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x75, 0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x72,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x03, 0x41, 0x72, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x03, 0x61, 0x72,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x07, 0x65, 0x78, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x35, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x74, 0x61, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x67, 0x6f, 0x2f, 0x61, 0x75,
	0x74, 0x6f, 0x70, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x72, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_autopeering_ars_proto_ars_proto_rawDescOnce sync.Once
	file_autopeering_ars_proto_ars_proto_rawDescData = file_autopeering_ars_proto_ars_proto_rawDesc
)

func file_autopeering_ars_proto_ars_proto_rawDescGZIP() []byte {
	file_autopeering_ars_proto_ars_proto_rawDescOnce.Do(func() {
		file_autopeering_ars_proto_ars_proto_rawDescData = protoimpl.X.CompressGZIP(file_autopeering_ars_proto_ars_proto_rawDescData)
	})
	return file_autopeering_ars_proto_ars_proto_rawDescData
}

var file_autopeering_ars_proto_ars_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_autopeering_ars_proto_ars_proto_goTypes = []interface{}{
	(*Ars)(nil), // 0: proto.Ars
}
var file_autopeering_ars_proto_ars_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_autopeering_ars_proto_ars_proto_init() }
func file_autopeering_ars_proto_ars_proto_init() {
	if File_autopeering_ars_proto_ars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_autopeering_ars_proto_ars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ars); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_autopeering_ars_proto_ars_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_autopeering_ars_proto_ars_proto_goTypes,
		DependencyIndexes: file_autopeering_ars_proto_ars_proto_depIdxs,
		MessageInfos:      file_autopeering_ars_proto_ars_proto_msgTypes,
	}.Build()
	File_autopeering_ars_proto_ars_proto = out.File
	file_autopeering_ars_proto_ars_proto_rawDesc = nil
	file_autopeering_ars_proto_ars_proto_goTypes = nil
	file_autopeering_ars_proto_ars_proto_depIdxs = nil
}
