// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopeering/peer/service/proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Mapping between a service ID and its tuple network_address
// e.g., map[autopeering:&{tcp, 198.51.100.1:80}]
type ServiceMap struct {
	Map                  map[string]*NetworkAddress `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ServiceMap) Reset()         { *m = ServiceMap{} }
func (m *ServiceMap) String() string { return proto.CompactTextString(m) }
func (*ServiceMap) ProtoMessage()    {}
func (*ServiceMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b10ad716ef970bf, []int{0}
}

func (m *ServiceMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMap.Unmarshal(m, b)
}
func (m *ServiceMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMap.Marshal(b, m, deterministic)
}
func (m *ServiceMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMap.Merge(m, src)
}
func (m *ServiceMap) XXX_Size() int {
	return xxx_messageInfo_ServiceMap.Size(m)
}
func (m *ServiceMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMap.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMap proto.InternalMessageInfo

func (m *ServiceMap) GetMap() map[string]*NetworkAddress {
	if m != nil {
		return m.Map
	}
	return nil
}

// The service type (e.g., tcp, upd) and the address (e.g., 198.51.100.1:80)
type NetworkAddress struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkAddress) Reset()         { *m = NetworkAddress{} }
func (m *NetworkAddress) String() string { return proto.CompactTextString(m) }
func (*NetworkAddress) ProtoMessage()    {}
func (*NetworkAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b10ad716ef970bf, []int{1}
}

func (m *NetworkAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkAddress.Unmarshal(m, b)
}
func (m *NetworkAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkAddress.Marshal(b, m, deterministic)
}
func (m *NetworkAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAddress.Merge(m, src)
}
func (m *NetworkAddress) XXX_Size() int {
	return xxx_messageInfo_NetworkAddress.Size(m)
}
func (m *NetworkAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAddress proto.InternalMessageInfo

func (m *NetworkAddress) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NetworkAddress) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*ServiceMap)(nil), "proto.ServiceMap")
	proto.RegisterMapType((map[string]*NetworkAddress)(nil), "proto.ServiceMap.MapEntry")
	proto.RegisterType((*NetworkAddress)(nil), "proto.NetworkAddress")
}

func init() {
	proto.RegisterFile("autopeering/peer/service/proto/service.proto", fileDescriptor_1b10ad716ef970bf)
}

var fileDescriptor_1b10ad716ef970bf = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x49, 0x2c, 0x2d, 0xc9,
	0x2f, 0x48, 0x4d, 0x2d, 0xca, 0xcc, 0x4b, 0xd7, 0x07, 0xd1, 0xfa, 0xc5, 0xa9, 0x45, 0x65, 0x99,
	0xc9, 0xa9, 0xfa, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x30, 0x9e, 0x1e, 0x98, 0x27, 0xc4, 0x0a, 0xa6,
	0x94, 0x3a, 0x19, 0xb9, 0xb8, 0x82, 0x21, 0x12, 0xbe, 0x89, 0x05, 0x42, 0x3a, 0x5c, 0xcc, 0xb9,
	0x89, 0x05, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x52, 0x10, 0xa5, 0x7a, 0x08, 0x79, 0x3d,
	0x20, 0x76, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x02, 0x29, 0x93, 0xf2, 0xe5, 0xe2, 0x80, 0x09, 0x08,
	0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x02, 0x75, 0x32, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0xda,
	0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x40, 0x31, 0x6e, 0x23, 0x51, 0xa8, 0x69,
	0x7e, 0xa9, 0x25, 0xe5, 0xf9, 0x45, 0xd9, 0x8e, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x41, 0x10,
	0x35, 0x56, 0x4c, 0x16, 0x8c, 0x4a, 0x76, 0x5c, 0x7c, 0xa8, 0x92, 0x42, 0x12, 0x5c, 0xec, 0x79,
	0x10, 0x11, 0xa8, 0xc1, 0x30, 0xae, 0x90, 0x10, 0x17, 0x4b, 0x41, 0x7e, 0x51, 0x09, 0xd8, 0x6c,
	0xde, 0x20, 0x30, 0xdb, 0xc9, 0x2e, 0xca, 0x26, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39,
	0x3f, 0x57, 0x3f, 0x33, 0xbf, 0x24, 0x31, 0x27, 0x35, 0x25, 0x1d, 0x18, 0x0e, 0x19, 0x99, 0x65,
	0xa9, 0x7a, 0xe9, 0xf9, 0xfa, 0xf8, 0x03, 0x28, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x79, 0xe6, 0x81, 0x49, 0x01, 0x00, 0x00,
}
