// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopeering/server/proto/packet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_00925e554f94f624, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Packet) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Packet) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "proto.Packet")
}

func init() {
	proto.RegisterFile("autopeering/server/proto/packet.proto", fileDescriptor_00925e554f94f624)
}

var fileDescriptor_00925e554f94f624 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0xce, 0xbf, 0xeb, 0xc2, 0x30,
	0x10, 0x05, 0x70, 0xfa, 0xfd, 0xd6, 0x42, 0x83, 0x2e, 0x99, 0x32, 0x28, 0x88, 0x20, 0x38, 0x35,
	0x83, 0x20, 0xce, 0xae, 0x2e, 0xd2, 0xd1, 0x45, 0xd2, 0xf6, 0x48, 0x43, 0x7f, 0x24, 0xa4, 0x97,
	0x42, 0xff, 0x7b, 0xeb, 0x15, 0xdc, 0x9c, 0xee, 0xdd, 0xe7, 0x2d, 0x8f, 0x1d, 0x55, 0x40, 0xeb,
	0x00, 0xbc, 0xe9, 0xb5, 0x1c, 0xc0, 0x8f, 0xe0, 0xa5, 0xf3, 0x16, 0xad, 0x74, 0xaa, 0x6c, 0x00,
	0x33, 0x7a, 0xf8, 0x8a, 0xce, 0xa1, 0x63, 0xc9, 0x83, 0x98, 0x73, 0x16, 0xe3, 0xe4, 0x40, 0x44,
	0xfb, 0xe8, 0xb4, 0xc9, 0x29, 0x7f, 0xac, 0x52, 0xa8, 0xc4, 0xdf, 0x6c, 0xeb, 0x9c, 0x32, 0xdf,
	0x31, 0xe6, 0x42, 0xd1, 0x9a, 0xf2, 0xd5, 0xc0, 0x24, 0xfe, 0xa9, 0x49, 0x17, 0xb9, 0xc3, 0xc4,
	0xb7, 0x2c, 0x1d, 0x8c, 0xee, 0x15, 0x06, 0x0f, 0x22, 0x5e, 0xda, 0x2f, 0xdc, 0xae, 0xcf, 0x8b,
	0x36, 0x58, 0x87, 0x22, 0x2b, 0x6d, 0x27, 0x8d, 0x45, 0xd5, 0x42, 0xa5, 0xe7, 0x85, 0xb5, 0x19,
	0x21, 0xd3, 0x56, 0xfe, 0x1a, 0x5f, 0x24, 0x74, 0xce, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34,
	0x1b, 0x88, 0x15, 0xdf, 0x00, 0x00, 0x00,
}
