// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopeering/discover/proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto2 "github.com/iotaledger/hive.go/autopeering/peer/proto"
	proto1 "github.com/iotaledger/hive.go/autopeering/peer/service/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	// protocol version number
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// unix time
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// endpoint of the sender; port and string form of the return address (e.g. "192.0.2.1", "[2001:db8::1]")
	SrcAddr string `protobuf:"bytes,3,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	SrcPort uint32 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	// endpoint of the receiver, this provides a way to discover the the external address (after NAT).
	DstAddr              string   `protobuf:"bytes,5,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	DstPort              uint32   `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127de36fdcd3874, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Ping) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *Ping) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Ping) GetDstAddr() string {
	if m != nil {
		return m.DstAddr
	}
	return ""
}

func (m *Ping) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

type Pong struct {
	// hash of the ping packet
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// services supported by the sender
	Services *proto1.ServiceMap `protobuf:"bytes,2,opt,name=services,proto3" json:"services,omitempty"`
	// endpoint of the receiver, this provides a way to discover the the external address (after NAT).
	DstAddr              string   `protobuf:"bytes,3,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	DstPort              uint32   `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127de36fdcd3874, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *Pong) GetServices() *proto1.ServiceMap {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Pong) GetDstAddr() string {
	if m != nil {
		return m.DstAddr
	}
	return ""
}

func (m *Pong) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

type DiscoveryRequest struct {
	// unix time
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127de36fdcd3874, []int{2}
}

func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(m, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DiscoveryResponse struct {
	// hash of the corresponding request
	ReqHash []byte `protobuf:"bytes,1,opt,name=req_hash,json=reqHash,proto3" json:"req_hash,omitempty"`
	// list of peers
	Peers                []*proto2.Peer `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d127de36fdcd3874, []int{3}
}

func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(m, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetReqHash() []byte {
	if m != nil {
		return m.ReqHash
	}
	return nil
}

func (m *DiscoveryResponse) GetPeers() []*proto2.Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*DiscoveryRequest)(nil), "proto.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "proto.DiscoveryResponse")
}

func init() {
	proto.RegisterFile("autopeering/discover/proto/message.proto", fileDescriptor_d127de36fdcd3874)
}

var fileDescriptor_d127de36fdcd3874 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0x3f, 0x4f, 0xfb, 0x30,
	0x14, 0x54, 0x7e, 0xe9, 0x9f, 0x5f, 0x5d, 0x90, 0x68, 0xa6, 0x50, 0x31, 0xd0, 0x4e, 0x1d, 0x20,
	0x41, 0xb0, 0x20, 0x36, 0x10, 0x03, 0x0b, 0x52, 0x31, 0x1b, 0x4b, 0xe5, 0x26, 0x4f, 0x89, 0x25,
	0x5a, 0xbb, 0xb6, 0x1b, 0x89, 0x2f, 0xc0, 0x87, 0xe1, 0x53, 0xf2, 0x6c, 0x27, 0xd0, 0x80, 0xca,
	0xe4, 0x9e, 0xef, 0xae, 0xbe, 0x7b, 0x2f, 0x64, 0xc6, 0xb6, 0x46, 0x48, 0x00, 0xc5, 0xd7, 0x45,
	0x9a, 0x73, 0x9d, 0x89, 0x0a, 0x54, 0x2a, 0x95, 0x30, 0x22, 0x5d, 0x81, 0xd6, 0xac, 0x80, 0xc4,
	0xa1, 0xa8, 0xeb, 0x8e, 0xf1, 0x64, 0xd7, 0x60, 0xcf, 0x5a, 0x6c, 0x7f, 0x7a, 0xe5, 0xf8, 0xec,
	0x97, 0x44, 0x83, 0xaa, 0x78, 0x06, 0xb5, 0xb4, 0x46, 0x5e, 0x3d, 0xfd, 0x08, 0x48, 0x67, 0x8e,
	0xca, 0x28, 0x26, 0x7d, 0x7c, 0x5b, 0x73, 0xb1, 0x8e, 0x83, 0xd3, 0x60, 0x76, 0x48, 0x1b, 0x18,
	0x9d, 0x90, 0x81, 0xe1, 0x98, 0xc6, 0xb0, 0x95, 0x8c, 0xff, 0x21, 0x17, 0xd2, 0xef, 0x8b, 0xe8,
	0x98, 0xfc, 0xd7, 0x2a, 0x5b, 0xb0, 0x3c, 0x57, 0x71, 0x88, 0xe4, 0x80, 0xf6, 0x11, 0xdf, 0x22,
	0x6c, 0x28, 0x29, 0x94, 0x89, 0x3b, 0xfe, 0x3f, 0x11, 0xcf, 0x11, 0x5a, 0x2a, 0xd7, 0xc6, 0xbb,
	0xba, 0xde, 0x85, 0xb8, 0x71, 0x59, 0xca, 0xb9, 0x7a, 0xde, 0x85, 0xd8, 0xba, 0xa6, 0xef, 0x36,
	0xac, 0xc0, 0xb0, 0xa8, 0x51, 0xb0, 0x59, 0x94, 0x4c, 0x97, 0x2e, 0xed, 0x01, 0xed, 0x23, 0x7e,
	0x40, 0x18, 0x9d, 0xe3, 0xa3, 0xbe, 0xa1, 0x76, 0x61, 0x87, 0x97, 0x23, 0x5f, 0x35, 0x79, 0xf6,
	0xd7, 0x8f, 0x4c, 0xd2, 0x2f, 0x49, 0x2b, 0x48, 0xb8, 0x3f, 0x48, 0xa7, 0x1d, 0xe4, 0x82, 0x1c,
	0xdd, 0xd7, 0xdb, 0x7a, 0xa3, 0xb0, 0xd9, 0xe2, 0x2c, 0xda, 0x63, 0x0a, 0x7e, 0x8c, 0x69, 0xfa,
	0x44, 0x46, 0x3b, 0x0e, 0x2d, 0xc5, 0x5a, 0xc3, 0x5f, 0x35, 0x26, 0xa4, 0x6b, 0x77, 0x67, 0x3b,
	0x84, 0xd8, 0x61, 0x58, 0x77, 0x98, 0xe3, 0x1d, 0xf5, 0xcc, 0xdd, 0xcd, 0xcb, 0x75, 0xc1, 0x4d,
	0xb9, 0x5d, 0x26, 0x99, 0x58, 0xa5, 0x5c, 0x18, 0xf6, 0x0a, 0x79, 0x81, 0xfb, 0x2e, 0x79, 0x05,
	0x49, 0x21, 0xd2, 0xfd, 0x1f, 0xd7, 0xb2, 0xe7, 0x8e, 0xab, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x97, 0x2e, 0xf6, 0x2e, 0x81, 0x02, 0x00, 0x00,
}
